[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
headless = true
runOnSave = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
base = "dark"
